# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: home
    url: /#top
    weight: 10
  - name: about
    url: about/
    weight: 30
  - name: user guide
    url: /user_guide
    weight: 40
    hasChildren: true
  - parent: user guide
    name: getting started
    url:  /getting_started
  - parent: user guide
    name: education
    url:  /education
  - parent: user guide
    name: examples
    url: examples/
  - name: tools
    url: /#tools
    weight: 20
    hasChildren: true
  - parent: tools
    name: comet_maths
    url: /comet_maths
  - parent: tools
    name: obsarray
    url: /obsarray
  - parent: tools
    name: punpy
    url: punpy/
  - name: news
    url: /news
    weight: 50
  - name: people
    url: admin/
    weight: 60