# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: home
    url: /#top
    weight: 10
  - name: tools
    url: /#features
    weight: 20
  - name: about
    url: /#solutions
    weight: 30
  - name: user guide
    weight: 40
    hasChildren: true
  - parent: user guide
    name: articles
    url: articles/
    name: examples
    url: examples/
  - name: news
    url: /#news
    weight: 50
  - name: people
    url: /#people
    weight: 60