# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: home
    url: /#top
    weight: 10
  - name: about
    url: about/
    weight: 20
  - name: user guide
    url: /user_guide
    weight: 30
    hasChildren: true
  - parent: user guide
    name: getting started
    url:  user-guide/getting_started
    weight: 30
  - parent: user guide
    name: theory
    url:  user-guide/theory/
    weight: 30
  - parent: user guide
    name: examples
    url: user-guide/examples/
    weight: 30
  - name: tools
    url: /#tools
    weight: 40
    hasChildren: true
  - parent: tools
    name: comet_maths
    url: /comet_maths
    weight: 40
  - parent: tools
    name: obsarray
    url: /obsarray
    weight: 40
  - parent: tools
    name: punpy
    url: punpy/
    weight: 40
  - name: news
    url: content/news/
    weight: 50
  - name: people
    url: authors/admin/
    weight: 60